
[types]

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.totemic]
			cedar = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.hexcasting]
			amethyst_edified = true
			aventurine_edified = true
			citrine_edified = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.byg]
			araucaria = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			joshua = true
			ripe_joshua = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			palo_verde = true
			pink_cherry = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			ripe_orchard = true
			silver_maple = true
			green_apple_skyris = true
			white_cherry = true
			yellow_birch = true
			yellow_spruce = true
			withering_oak = true
			flowering_nightshade = true
			firecracker = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			flowering_baobab = true
			ripe_baobab = true
			flowering_joshua = true
			flowering_skyris = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.malum]
			runewood = true
			soulwood = true

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			blossom = true
			bamboo = true
			ancient = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.hexcasting]
			edified = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.byg]
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true

		[types.wood_type.totemic]
			cedar = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.mcwbridges]
			log_bridge_stair = true
			rail_bridge = true
			bridge_pier = true
			rope_bridge = true
			rope_bridge_stair = true
			log_bridge_middle = true

		[entries.wood_type.mcwfences]
			horse_fence = true
			highley_gate = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true
			picket_fence = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true

		[entries.wood_type.mcwpaths]
			planks_path = true

